# Menggunakan base image PHP 8.2 dengan Apache
FROM php:8.2-apache

# Mengatur working directory di dalam container
WORKDIR /var/www/html

# Menginstal modul sistem operasi yang dibutuhkan oleh Laravel & Node.js
RUN apt-get update && apt-get install -y \
    libpng-dev \
    zlib1g-dev \
    libxml2-dev \
    libzip-dev \
    libonig-dev \
    zip \
    curl \
    unzip \
    git \
    nodejs \
    npm

# Menginstal ekstensi PHP yang dibutuhkan Laravel
RUN docker-php-ext-install pdo_mysql exif pcntl bcmath gd zip

# Menginstal ekstensi MongoDB (KARENA MAS ARYO PAKAI MONGODB)
RUN pecl install mongodb && docker-php-ext-enable mongodb

# Menginstal Composer secara global
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Meng-copy seluruh kode aplikasi Tigo dari laptop ke dalam container
COPY . /var/www/html

# Mengatur permission agar web server (Apache) bisa menulis ke folder storage
RUN chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
RUN chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache

# Mengatur Document Root Apache ke folder public Laravel
ENV APACHE_DOCUMENT_ROOT /var/www/html/public
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Mengaktifkan mod_rewrite Apache (wajib untuk routing Laravel)
RUN a2enmod rewrite

# ---------------------------------------------------------
# PROSES BUILD
# ---------------------------------------------------------

# 1. Instal depedensi PHP (abaikan dev)
# 1. Instal depedensi PHP (abaikan dev) dan abaikan peringatan platform
RUN composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev --ignore-platform-reqs

# 2. Instal depedensi Node.js & Build React/Inertia (Vite)
RUN npm install
RUN npm run build

# Mengekspos port 80 untuk web server
EXPOSE 80